ANSWER(A network designer must provide a rationale to a customer for a design which will move an enterprise from a flat network topology to a hierarchical network topology. Which two features of the hierarchical design make it the better choice? (Choose two.), easier simpler)
ANSWER(What is a collapsed core in a network design?, of the distribution)
ANSWER(What is a definition of a two-tier LAN network design?, distribution)
ANSWER(What is a basic function of the Cisco Borderless Architecture distribution layer?, Layer 3)
ANSWER(Which two previously independent technologies should a network administrator attempt to combine after choosing to upgrade to a converged network infrastructure? (Choose two.), user VoIP)
ANSWER(A local law firm is redesigning the company network so that all 20 employees can be connected to a LAN and to the Internet. The law firm would prefer a low cost and easy solution for the project. What type of switch should be selected?, fixed)
ANSWER(What are two advantages of modular switches over fixed-configuration switches? (Choose two.), increased need)
ANSWER(Which type of address does a switch use to build the MAC address table?, source MAC)
ANSWER(Which network device can be used to eliminate collisions on an Ethernet network?, switch)
ANSWER(What two criteria are used by a Cisco LAN switch to decide how to forward Ethernet frames? (Choose two.), ingress MAC)
ANSWER(Refer to the exhibit. Consider that the main power has just been restored. PC3 issues a broadcast IPv4 DHCP request. To which port will SW1 forward this request?, 123)
ANSWER(What is one function of a Layer 2 switch?, determines)
ANSWER(Refer to the exhibit. How is a frame sent from PCA forwarded to PCC if the MAC address table on switch SW1 is empty?, on SW1)
ANSWER(A small publishing company has a network design such that when a broadcast is sent on the LAN, 200 devices receive the transmitted broadcast. How can the network administrator reduce the number of devices that receive broadcast traffic?, Segment)
ANSWER(Refer to the exhibit.How many broadcast domains are displayed ?, 2^3)
ANSWER(Which solution would help a college alleviate network congestion due to collisions?, density)
ANSWER(Which network device can serve as a boundary to divide a Layer 2 broadcast domain?, router)
ANSWER(What is the destination address in the header of a broadcast frame?, Press F)
ANSWER(Which statement describes a result after multiple Cisco LAN switches are interconnected?, expands)
ANSWER(What does the term “port density” represent for an Ethernet switch?, available)
ANSWER(What are two reasons a network administrator would segment a network with a Layer 2 switch? (Choose two.), bandwidth segments)
ANSWER(What type of network uses one common infrastructure to carry voice, data, and video signals?, converged)
